name: Notepad
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^1.2.0
  flutter_launcher_icons: ^0.9.1

  cupertino_icons: ^1.0.2

  sqflite: ^2.0.0+3
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3

  google_sign_in: ^5.0.3
  font_awesome_flutter: '>= 4.7.0'

flutter_native_splash:
  color: "#000000"
  image: "lib/assets/app/anotacoes 1.png"
  android: true
  ios: true

flutter_icons:
  image_path: "lib/assets/app/anotacoes 2.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_backgroud: "#ffffff"
  adaptive_icon_foreground: "lib/assets/app/anotacoes 2.png"

flutter:
  uses-material-design: true